services:
  whisper:
    environment:
      - ALGORITHM=${ALGORITHM}
      - SERVER_NAME=${SERVER_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - SERVER_HOST=${SERVER_HOST}
      - POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL}
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "7860:7860"

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"